### ISSUE TITLE
Doesnt work in unity 6000.4.8f1

### ISSUE THREAD

**Issue by FireBlast2020** [Zallist/unity.zallist.universal-simple-lit-shadergraph-target#31]
```
com.zallist.universal-shadergraph-extensions@94d5546221e8\Editor\ShaderGraph\Targets\UniversalSimpleLitSubTarget.cs(876,42): 
error CS0117: 'CoreKeywordDescriptors' does not contain a definition for 'ForwardPlus'
```

Got this error upon importing, tried to fix and couldnt get it working
